"""initial_schema

Revision ID: 2f83c6bebc57
Revises: 
Create Date: 2026-03-05 18:18:18.331990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f83c6bebc57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_batiment_site_nom_active'), table_name='batiments', sqlite_where=sa.text('"deleted_at" IS NULL'))
    op.drop_index(op.f('uq_compteur_meter_id_active'), table_name='compteurs', sqlite_where=sa.text('"meter_id" IS NOT NULL AND "deleted_at" IS NULL'))
    op.drop_index(op.f('uq_delivery_point_code_active'), table_name='delivery_points', sqlite_where=sa.text('"code" IS NOT NULL AND "deleted_at" IS NULL'))
    op.drop_index(op.f('uq_org_siren_active'), table_name='organisations', sqlite_where=sa.text('"siren" IS NOT NULL AND "deleted_at" IS NULL'))
    op.drop_index(op.f('uq_portefeuille_ej_nom_active'), table_name='portefeuilles', sqlite_where=sa.text('"deleted_at" IS NULL'))
    op.drop_index(op.f('uq_site_portefeuille_siret_active'), table_name='sites', sqlite_where=sa.text('"siret" IS NOT NULL AND "deleted_at" IS NULL'))
    op.drop_index(op.f('ix_tertiaire_dq_issue_efa_id'), table_name='tertiaire_data_quality_issue')
    op.drop_index(op.f('uq_tertiaire_declaration_efa_year'), table_name='tertiaire_declaration')
    op.drop_index(op.f('ix_tertiaire_efa_statut'), table_name='tertiaire_efa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tertiaire_efa_statut'), 'tertiaire_efa', ['statut'], unique=False)
    op.create_index(op.f('uq_tertiaire_declaration_efa_year'), 'tertiaire_declaration', ['efa_id', 'year'], unique=1)
    op.create_index(op.f('ix_tertiaire_dq_issue_efa_id'), 'tertiaire_data_quality_issue', ['efa_id'], unique=False)
    op.create_index(op.f('uq_site_portefeuille_siret_active'), 'sites', ['portefeuille_id', 'siret'], unique=1, sqlite_where=sa.text('"siret" IS NOT NULL AND "deleted_at" IS NULL'))
    op.create_index(op.f('uq_portefeuille_ej_nom_active'), 'portefeuilles', ['entite_juridique_id', 'nom'], unique=1, sqlite_where=sa.text('"deleted_at" IS NULL'))
    op.create_index(op.f('uq_org_siren_active'), 'organisations', ['siren'], unique=1, sqlite_where=sa.text('"siren" IS NOT NULL AND "deleted_at" IS NULL'))
    op.create_index(op.f('uq_delivery_point_code_active'), 'delivery_points', ['code'], unique=1, sqlite_where=sa.text('"code" IS NOT NULL AND "deleted_at" IS NULL'))
    op.create_index(op.f('uq_compteur_meter_id_active'), 'compteurs', ['meter_id'], unique=1, sqlite_where=sa.text('"meter_id" IS NOT NULL AND "deleted_at" IS NULL'))
    op.create_index(op.f('uq_batiment_site_nom_active'), 'batiments', ['site_id', 'nom'], unique=1, sqlite_where=sa.text('"deleted_at" IS NULL'))
    # ### end Alembic commands ###
